class Dictionaries:
    cf_columns = {
        "id": "CF ID",
        "assessor_group_id": "Assessor Group ID",
        "assessor_id": "Assessor ID",
        "name": "Chemical Name",
        "cas_rn": "CAS Number",
        "inci": "INCI",
        "status": "Status",
        "smiles": "SMILES",
        "common_impurities": "Common Impurities",
        "voc": "VOC",
        "molecular_weight": "Molecular Weight",
        "vapor_pressure": "Vapor Pressure",
        "octanol_water": "Octanol-Water Partition Coefficient",
        "boiling_point": "Boiling Point",
        "solubility": "Solubility",
        "applications": "Applications",
        "inserted_at": "Inserted At",
        "updated_at": "Updated At",
        "particle_size_start": "Particle Size Start",
        "particle_size_end": "Particle Size End",
        "ph": "pH",
        "auditor_id": "Auditor ID",
        "primary_application": "Primary Application",
        "secondary_application": "Secondary Application",
        "other_applications": "Other Applications",
        "summary": "Summary",
        "hazard_level": "Hazard Level",
        "polymer": "Polymer",
        "does_not_undergo_hydrolysis": "Does Not Undergo Hydrolysis",
        "has_gt_five_hydrogen_bond_donors": "Has >5 Hydrogen Bond Donors",
        "has_gt_ten_hydrogen_bond_acceptors": "Has >10 Hydrogen Bond Acceptors",
        "is_c2c_banned": "C2C Banned",
        "chemical_class": "Chemical Class",
        "manual_rollup_score": "C2C Score",
        "references": "References",
        "degrades_at_temperature": "Degrades at Temperature",
        "sources": "Sources",
        "melting_point": "Melting Point",
        "dissociation_constant": "Dissociation Constant",
        "solubility_temperature": "Solubility Temperature",
        "inorganic_chemical": "Inorganic Chemical",
        "alternate_names": "Alternate Names",
        "common_trade_names": "Common Trade Names",
        "functional_uses": "Functional Uses",
        "verification_date": "Verification Date",
        "additional_casrns": "Additional CAS",
        "exempt_voc": "Exempt VOC",
        "pharos_id": "Pharos ID",
        "scil_status": "SCIL Status",
        "manual_hazard_band_score": "Hazard Band",
        "pharos_greenscreen_score": "Pharos GreenScreen Score",
        "nams": "NAMS",
        "pods": "PODS",
        "regulatory_summary": "Regulatory Summary",
        "vapor_pressure_qualifier": "Vapor Pressure Qualifier",
        "solubility_qualifier": "Solubility Qualifier",
        "boiling_point_qualifier": "Boiling Point Qualifier",
        "degrades_at_temperature_qualifier": "Degrades at Temperature Qualifier",
        "tco_status": "TCO Status",
        "is_free": "Free CHA?",
        "botanical": "Botanical",
        "ec_number": "EC Number",
        "in_progress": "In Progress",
        "price": "Price",
        "pharos_ghs_h_statements": "Pharos GHS H Statements",
        "color_index_number": "Color Index Number",
        "dispersion_solubility": "Dispersion Solubility",
        "polar_solubility": "Polar Solubility",
        "hydrogen_bonding_solubility": "Hydrogen Bonding Solubility",
        "total_hansen_solubility": "Total Hansen Solubility",
        "vapor_pressure_unit": "Vapor Pressure Unit",
        "vapor_pressure_temperature": "Vapor Pressure Temperature",
        "vapor_pressure_predicted": "Predicted Vapor Pressure",
        "vapor_pressure_predicted_qualifier": "Predicted Vapor Pressure Qualifier",
        "vapor_pressure_predicted_unit": "Predicted Vapor Pressure Unit",
        "vapor_pressure_predicted_temperature": "Predicted Vapor Pressure Temperature",
        "boiling_point_predicted": "Predicted Boiling Point",
        "boiling_point_predicted_qualifier": "Predicted Boiling Point Qualifier",
        "is_provisional": "Provisional?",
        "additional_chemical_characterization": "Additional Chemical Characterization",
        "sponsor": "Sponsor",
        "direct_sponsorship": "Direct Sponsorship",
        "project": "Project",
        "is_provisional_date": "Provisional Date",
        "list_based_c2c_score": "List Based C2C Score",
        "list_based_hazard_score": "List Based Hazard Score"
    }

    pharos_columns = {
        "id": "Pharos ID",
        "casrn": "CAS Number",
        "name": "Chemical Name",
        "greenscreen_list_translator_score": "GS-LT Score",
        "scil_status": "SCIL Status",
        "tco_status": "TCO Status",
        "hazard_band_score": "Hazard Band"
    }

    cf_status = {
        "verified": "Verified",
        "awaiting_verifier_response": "Awaiting Verifier",
        "awaiting_assessor_response": "Awaiting Assessor",
        "in_review": "In Review",
        "submitted": "Submitted",
        "draft": "Draft",
        "screening_only": "Curated Screening"
    }

    manual_hazard_band_score = {
        "z": "?",
        "a": "A",
        "b": "B",
        "b_c": "B_C",
        "c": "C",
        "d": "D",
        "f": "F",
        "ip": "IP"
    }

    scil_status = {
        "green_circle": "Green Full Circle",
        "green_half_circle": "Green Half Circle",
        "yellow_triangle": "Yellow Triangle",
        "grey_square": "Grey Square",
        "tentative": "Tentative",
        "unlisted": "Unlisted"
    }

    tco_status = {
        "bm3": "BM-3",
        "bm2": "BM-2",
        "tentative": "Tentative"
    }
